import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readData, root, validate } from './validate.mjs';
import { readmeFile, caseAnchor, orderEntries, textFor, projectEntry } from './catalog.mjs';

const escape = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const fmt = value => value === null ? '—' : value.toLocaleString('en-US');
const fence = value => {
  const ticks = '`'.repeat(Math.max(3, ...Array.from(value.matchAll(/`+/g), m => m[0].length + 1)));
  return `${ticks}text\n${value}\n${ticks}`;
};

export function generate(entries, site, config) {
  const ordered = orderEntries(entries);
  const outputs = new Map();
  const languages = (id, prefix = '') => config.locales.map(l => `[${l.name}](${prefix}${readmeFile(l.id)}${id ? `#${caseAnchor(id)}` : ''})`).join(' · ');
  const preview = (e, locale, width = 640) => e.previews.map(p => `<a href="${escape(p.source_url)}"><img src="${escape(p.url)}" width="${width}" alt="${escape(textFor(e, locale).title)} — ${escape(p.credit)} — ${escape(config.messages[locale].imageAlt)}" loading="lazy"></a>`).join('\n\n');
  const generated = '<!-- Generated by scripts/build.mjs. Edit data/prompts/*.json, data/site.json, and data/locales.json. -->';
  for (const locale of config.locales) {
    const lang = locale.id, t = config.messages[lang];
    const lines = [generated, `<a href="${escape(site.url)}"><img src="assets/banner.svg" width="100%" alt="Awesome GPT Image 2.5 Prompts"></a>`, '', '# Awesome GPT Image 2.5 Prompts', '', languages(), '', t.intro, '', `**${entries.length} ${t.count} · ${config.locales.length} ${t.languages}**`, '', `${t.maintainer}: **[Image 2.5 — image-2-5.com](${site.url})**`, '', t.evidenceText, '', t.sortText, '', `## ${t.how}`, '', t.howText, '', t.translationNote, '', '<a id="collection"></a>', `## ${t.collection}`, '', `### ${t.categories}`, ''];
    for (const c of site.categories) {
      const label = c[lang] ?? (lang === 'zh-CN' ? c.zh : c.en);
      lines.push(`- [${label}](#category-${c.id})`);
    }
    for (const c of site.categories) {
      lines.push('', `<a id="category-${c.id}"></a>`, `### ${c[lang] ?? (lang === 'zh-CN' ? c.zh : c.en)}`, '');
      for (const e of ordered.filter(e => e.category === c.id)) lines.push(`- [${textFor(e, lang).title}](#${caseAnchor(e.id)})`);
    }
    for (const e of ordered) {
      const content = textFor(e, lang);
      lines.push('', '---', '', `<a id="${caseAnchor(e.id)}"></a>`, `## ${content.title}`, '', preview(e, lang), '', languages(e.id), '', content.summary, '', `**${t[e.prompt.kind]} · ${t[e.mode]} · ${e.verification.independently_tested ? `[${t.tested}](${e.verification.test_url})` : t.untested}**`, '', `[@${e.source.author}](${e.source.url}) · [${t.promptSource}](${e.source.prompt_url}) · [${t.modelEvidence}](${e.model.evidence_url})`, '', `${t.sourceLanguage}: **${e.prompt.original_language ?? t.unknown}** · ${t.postLanguage}: **${e.source.post_language ?? t.unknown}**`, '', `${fmt(e.engagement.likes)} ${t.likes} · ${fmt(e.engagement.bookmarks)} ${t.bookmarks} · ${fmt(e.engagement.reposts)} ${t.reposts} · ${fmt(e.engagement.views)} ${t.views}`, '', `${t.snapshot}: ${e.engagement.observed_at} · ${t.sourceChecked}: ${e.source.checked_at}`, '', `### ${t.inputs}`, '', ...(content.inputs.length ? content.inputs.map(v => `- ${v}`) : [t.noInputs]), '', '<details>', `<summary>${escape(t.prompt)}</summary>`, '');
      content.steps.forEach((value, i) => lines.push(content.steps.length > 1 ? `#### ${t.step} ${i + 1}` : '', '', fence(value), ''));
      lines.push('</details>', '', '<details>', `<summary>${escape(t.originalText)}</summary>`, '');
      if (e.prompt.original_steps?.length) e.prompt.original_steps.forEach(value => lines.push(fence(value), ''));
      else lines.push(t.originalUnavailable, '');
      lines.push(`[${t.promptSource}](${e.source.prompt_url})`, '', '</details>', '', `### ${t.notes}`, '', ...content.notes.map(v => `- ${v}`));
      if (e.source.disclosure) lines.push(`- ${t.disclosure}: ${/paid[- ]partnership/i.test(e.source.disclosure) ? t.paidPartnership : e.source.disclosure}`);
      lines.push('', `[${t.open}](${site.promptDestination}) · [${t.top}](#collection)`);
    }
    lines.push('', '---', '', `## ${t.data}`, '', t.dataText, '', '[JSON catalog](data/catalog.json) · [Data contract](docs/DATA_FORMAT.md) · [Curation](docs/CURATION.md) · [Contributing](CONTRIBUTING.md) · [Credits](ACKNOWLEDGEMENTS.md)', '', '```bash', 'npm run build', 'npm run check', '```', '', t.rights, '', '[MIT](LICENSE) · [Content policy](CONTENT_POLICY.md)', '', t.independent, '', `${t.maintainer}: [Image 2.5](${site.url}) · [${site.contact}](mailto:${site.contact})`, '');
    outputs.set(readmeFile(lang), lines.join('\n'));
  }
  for (const e of entries) {
    outputs.set(`prompts/${e.id}.md`, [generated, `# ${e.title.en}`, '', preview(e, 'en'), '', languages(e.id, '../'), '', e.summary.en, '', `[Source: @${e.source.author}](${e.source.url}) · [Prompt source](${e.source.prompt_url})`, '', '<a id="中文"></a>', '## 中文', '', preview(e, 'zh-CN'), '', `[查看图片与完整中文提示词](../README.zh-CN.md#${caseAnchor(e.id)})`, '', languages(e.id, '../'), ''].join('\n'));
  }
  outputs.set('data/catalog.json', JSON.stringify({ schema_version: 1, source_checked_through: entries.map(e => e.source.checked_at).sort().at(-1).slice(0, 10), website: site.url, prompt_destination: site.promptDestination, repository: site.repository, locales: config.locales, categories: site.categories, entries: ordered.map(e => projectEntry(e, config.locales.map(l => l.id))) }, null, 2) + '\n');
  return outputs;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { entries, site, locales } = readData();
  const errors = validate(entries, site, locales);
  if (errors.length) throw new Error(errors.join('\n'));
  const outputs = generate(entries, site, locales), stale = [], check = process.argv.includes('--check');
  for (const [file, content] of outputs) {
    const full = path.join(root, file);
    if (check) {
      if (!fs.existsSync(full) || fs.readFileSync(full, 'utf8') !== content) stale.push(file);
    } else {
      fs.mkdirSync(path.dirname(full), { recursive: true });
      fs.writeFileSync(full, content);
    }
  }
  for (const file of fs.readdirSync(path.join(root, 'prompts')).filter(f => f.endsWith('.md'))) {
    if (!outputs.has(`prompts/${file}`)) stale.push(`prompts/${file} (orphan; review before removal)`);
  }
  if (stale.length) { console.error(`Generated files are stale. Run npm run build:\n${stale.join('\n')}`); process.exitCode = 1; }
  else console.log(`${check ? 'Checked' : 'Generated'} ${outputs.size} catalog and documentation files.`);
}
