import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { readData, root, validate } from './validate.mjs';
import { readmeFile, caseAnchor, orderEntries, textFor, exportEntry, placement, featuredEntries, qualityScore, websiteLink } from './catalog.mjs';

const escape = s => String(s).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const fmt = value => value === null ? '—' : value.toLocaleString('en-US');
const fence = value => {
  const ticks = '`'.repeat(Math.max(3, ...Array.from(value.matchAll(/`+/g), m => m[0].length + 1)));
  return `${ticks}text\n${value}\n${ticks}`;
};
const generated = '<!-- Generated by scripts/build.mjs. Edit data/prompts/*.json, data/site.json, and data/locales.json. -->';

export function generate(entries, site, config) {
  const ordered = orderEntries(entries), outputs = new Map();
  const active = ordered.filter(e => placement(e) !== 'held');
  const main = active.filter(e => placement(e) === 'main'), explore = active.filter(e => placement(e) === 'explore');
  const held = ordered.filter(e => placement(e) === 'held');
  const languages = (id, prefix = '') => config.locales.map(l => `[${l.name}](${prefix}${readmeFile(l.id)}${id ? `#user-content-${caseAnchor(id)}` : ''})`).join(' · ');
  const preview = (e, locale, width = 640) => e.previews.map(p => `<a href="${escape(p.source_url)}"><img src="${escape(p.url)}" width="${width}" alt="${escape(textFor(e, locale).title)} — ${escape(p.credit)} — ${escape(config.messages[locale].imageAlt)}" loading="lazy"></a>`).join('\n\n');
  const labels = (e, t) => [...e.curation.content_flags.map(flag => t[flag]), ...(qualityScore(e) < 65 ? [t.educational] : [])].join(' · ');
  function content(e, lang, { prefix = '', cta = true, position = 'case' } = {}) {
    const t = config.messages[lang], text = textFor(e, lang);
    const lines = [preview(e, lang), '', text.summary, '', `**${t[e.prompt.kind]} · ${t[e.mode]} · ${e.verification.independently_tested ? `[${t.tested}](${e.verification.test_url})` : t.untested}**`, '', `### ${t.inputs}`, '', ...(text.inputs.length ? text.inputs.map(v => `- ${v}`) : [t.noInputs])];
    if (e.references?.length) lines.push('', `${t.references}: ${e.references.map((r, i) => `[${i + 1}](${r.url})`).join(' · ')}`);
    lines.push('', '<details>', `<summary>${escape(t.prompt)}</summary>`, '');
    text.steps.forEach((value, i) => lines.push(text.steps.length > 1 ? `#### ${t.step} ${i + 1}` : '', '', fence(value), ''));
    if (cta) {
      const target = websiteLink(site, { id: e.id, locale: lang, position });
      lines.push(`[${target.detail ? t.detail : t.browse}](${target.url})`, '');
    }
    lines.push('</details>', '', `### ${t.adaptTitle}`, '', t[`adapt${e.mode[0].toUpperCase()}${e.mode.slice(1)}`], '', `### ${t.notes}`, '', ...text.notes.map(v => `- ${v}`), '', '<details>', `<summary>${escape(t.evidence)}</summary>`, '', `**${t.review}: ${qualityScore(e)}/100 · ${e.curation.reviewed_at}**`, '', `[${t.review}](${prefix}docs/CURATION.md)`, '', `[${e.source.platform === 'x' ? '@' : ''}${e.source.author}](${e.source.url}) · [${t.promptSource}](${e.source.prompt_url}) · [${t.modelEvidence}](${e.model.evidence_url})`, '', `${t.sourceLanguage}: **${e.prompt.original_language ?? t.unknown}** · ${t.postLanguage}: **${e.source.post_language ?? t.unknown}**`, '', `${fmt(e.engagement.likes)} ${t.likes} · ${fmt(e.engagement.bookmarks)} ${t.bookmarks} · ${fmt(e.engagement.reposts)} ${t.reposts} · ${fmt(e.engagement.views)} ${t.views}`, '', `${t.snapshot}: ${e.engagement.observed_at} · ${t.sourceChecked}: ${e.source.checked_at}`);
    if (e.source.disclosure) lines.push('', `${t.disclosure}: ${/paid[- ]partnership/i.test(e.source.disclosure) ? t.paidPartnership : e.source.disclosure}`);
    lines.push('', `### ${t.originalText}`, '');
    if (e.prompt.original_steps?.length) e.prompt.original_steps.forEach(value => lines.push(fence(value), ''));
    else lines.push(t.originalUnavailable, '');
    lines.push('</details>');
    return lines;
  }
  function card(e, lang) {
    const t = config.messages[lang], exploratory = placement(e) === 'explore';
    const lines = ['', '---', '', `<a id="${caseAnchor(e.id)}"></a><a id="user-content-${caseAnchor(e.id)}"></a>`, `## ${textFor(e, lang).title}`, '', languages(e.id), ''];
    if (exploratory) lines.push(`<details>`, `<summary>${escape(labels(e, t))} — ${escape(t.exploreTitle)}</summary>`, '');
    lines.push(...content(e, lang));
    if (exploratory) lines.push('', '</details>');
    lines.push('', `[${t.top}](#collection)`);
    return lines;
  }
  for (const { id: lang } of config.locales) {
    const t = config.messages[lang];
    const gallery = websiteLink(site, { locale: lang, position: 'banner' }).url;
    const lines = [generated, `<a href="${escape(gallery)}"><img src="assets/banner.svg" width="100%" alt="Awesome GPT Image 2.5 Prompts"></a>`, '', '# Awesome GPT Image 2.5 Prompts', '', languages(), '', t.intro, '', `**${active.length} ${t.count} · ${config.locales.length} ${t.languages}** · [${t.browse}](${websiteLink(site, { locale: lang, position: 'intro' }).url}) · ${t.maintainer}: [Image 2.5](${websiteLink(site, { locale: lang, position: 'maintainer', home: true }).url})`, '', `## ${t.featuredTitle}`, ''];
    for (const e of featuredEntries(active)) lines.push(`- [${textFor(e, lang).title}](#${caseAnchor(e.id)}) — ${textFor(e, lang).summary}`);
    lines.push('', t.sortText, '', t.evidenceText, '', '<a id="how-to-use"></a>', `## ${t.how}`, '', t.howText, '', t.translationNote, '', '<a id="collection"></a>', `## ${t.collection}`, '', `### ${t.modes}`, '');
    for (const mode of ['generate', 'edit', 'workflow']) lines.push(`- [${t[mode]}](#mode-${mode})`);
    lines.push('', `### ${t.categories}`, '');
    for (const c of site.categories) lines.push(`- [${c[lang]}](#category-${c.id})`);
    for (const c of site.categories) {
      lines.push('', `<a id="category-${c.id}"></a>`, `### ${c[lang]}`, '');
      for (const e of main.filter(e => e.category === c.id)) lines.push(`- [${textFor(e, lang).title}](#${caseAnchor(e.id)})`);
    }
    for (const mode of ['generate', 'edit', 'workflow']) {
      lines.push('', `<a id="mode-${mode}"></a>`, '<details>', `<summary>${escape(t[mode])}</summary>`, '');
      for (const e of main.filter(e => e.mode === mode)) lines.push(`- [${textFor(e, lang).title}](#${caseAnchor(e.id)})`);
      lines.push('', '</details>');
    }
    for (const e of main) lines.push(...card(e, lang));
    if (explore.length) {
      lines.push('', '---', '', '<a id="explore"></a>', `## ${t.exploreTitle}`, '', t.exploreText);
      for (const e of explore) lines.push(...card(e, lang));
    }
    if (held.length) {
      lines.push('', '---', '', `## ${t.heldTitle}`, '', t.heldText);
      for (const e of held) lines.push('', `<a id="${caseAnchor(e.id)}"></a><a id="user-content-${caseAnchor(e.id)}"></a>`, `- [${textFor(e, lang).title}](prompts/${e.id}.md)`);
    }
    lines.push('', '---', '', '<a id="data-for-your-app"></a>', `## ${t.data}`, '', t.dataText, '', '[JSON catalog](data/catalog.json) · [Data contract](docs/DATA_FORMAT.md) · [Curation](docs/CURATION.md) · [Contributing](CONTRIBUTING.md) · [Credits](ACKNOWLEDGEMENTS.md)', '', '```bash', 'npm run build', 'npm run check', '```', '', t.rights, '', '[MIT](LICENSE) · [Content policy](CONTENT_POLICY.md)', '', t.independent, '', '<a id="support"></a>', `[${site.contact}](mailto:${site.contact})`, '');
    outputs.set(readmeFile(lang), lines.join('\n'));
  }
  for (const e of entries) {
    const lines = [generated, `# ${e.title.en}`, '', languages(e.id, '../'), ''];
    if (placement(e) === 'held') lines.push(config.messages.en.heldText, '', e.curation.notice.en, '', '<a id="中文"></a>', '## 中文', '', config.messages['zh-CN'].heldText, '', e.curation.notice['zh-CN'], '');
    else {
      for (const lang of ['en', 'zh-CN']) {
        const t = config.messages[lang];
        if (lang === 'zh-CN') lines.push('', '<a id="中文"></a>', '## 中文', '');
        if (placement(e) === 'explore') lines.push('<details>', `<summary>${escape(labels(e, t))} — ${escape(t.exploreTitle)}</summary>`, '');
        lines.push(...content(e, lang, { prefix: '../', cta: lang === 'en', position: 'detail' }));
        if (placement(e) === 'explore') lines.push('', '</details>');
      }
    }
    outputs.set(`prompts/${e.id}.md`, lines.join('\n').trimEnd() + '\n');
  }
  outputs.set('data/catalog.json', JSON.stringify({ schema_version: 2,
    source_checked_through: active.map(e => e.source.checked_at).sort().at(-1)?.slice(0, 10) ?? null,
    website: site.url, prompt_destination: site.promptDestination, repository: site.repository, locales: config.locales,
    categories: site.categories, featured_ids: featuredEntries(active).map(e => e.id),
    entries: active.map(e => exportEntry(e, site)), withheld: held.map(e => ({ id: e.id, reason: e.curation.rationale })) }, null, 2) + '\n');
  return outputs;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const { entries, site, locales } = readData(), errors = validate(entries, site, locales);
  if (errors.length) throw new Error(errors.join('\n'));
  const outputs = generate(entries, site, locales), stale = [], check = process.argv.includes('--check');
  for (const [file, content] of outputs) {
    const full = path.join(root, file);
    if (check) { if (!fs.existsSync(full) || fs.readFileSync(full, 'utf8') !== content) stale.push(file); }
    else { fs.mkdirSync(path.dirname(full), { recursive: true }); fs.writeFileSync(full, content); }
  }
  for (const file of fs.readdirSync(path.join(root, 'prompts')).filter(f => f.endsWith('.md'))) if (!outputs.has(`prompts/${file}`)) stale.push(`prompts/${file} (orphan; review before removal)`);
  if (stale.length) { console.error(`Generated files are stale. Run npm run build:\n${stale.join('\n')}`); process.exitCode = 1; }
  else console.log(`${check ? 'Checked' : 'Generated'} ${outputs.size} catalog and documentation files.`);
}
