import fs from 'node:fs';
import path from 'node:path';
import { readData, root, validate } from './validate.mjs';

const { entries, site } = readData();
const errors = validate(entries, site);
if (errors.length) throw new Error(errors.join('\n'));
const ordered = [...entries].sort((a, b) => (b.engagement.likes ?? -1) - (a.engagement.likes ?? -1) || a.id.localeCompare(b.id, 'en'));
const fmt = v => v === null ? '—' : v.toLocaleString('en-US');
const escape = s => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const table = s => s.replaceAll('|', '\\|').replaceAll('\n', ' ');
const date = entries.map(e => e.source.checked_at.slice(0, 10)).sort().at(-1);
const kind = (e, lang) => ({ original: { en: 'Original prompt', zh: '原始英文 prompt' }, adaptation: { en: 'Editor adaptation', zh: '编辑改写' }, translation: { en: 'Translation', zh: '翻译' } }[e.prompt.kind][lang]);
const mode = (e, lang) => ({ generate: { en: 'Text to image', zh: '文生图' }, edit: { en: 'Reference edit', zh: '参考图编辑' }, workflow: { en: 'Multi-step workflow', zh: '多步骤工作流' } }[e.mode][lang]);
const link = (id, lang = 'en') => `prompts/${id}.md${lang === 'zh' ? '#中文' : ''}`;
const badge = (label, message, color) => `https://img.shields.io/badge/${encodeURIComponent(label).replaceAll('-', '--')}-${encodeURIComponent(message).replaceAll('-', '--')}-${color}`;
const outputs = new Map();

function preview(e, lang, width = 280) {
  if (!e.previews.length) return '';
  const p = e.previews[0];
  return `<a href="${escape(p.source_url)}"><img src="${escape(p.url)}" width="${width}" alt="${escape(e.title[lang])} — ${escape(p.credit)} source example" loading="lazy"></a>`;
}

function readme(lang) {
  const zh = lang === 'zh';
  const t = (en, cn) => zh ? cn : en;
  const original = entries.filter(e => e.prompt.kind === 'original').length;
  const lines = [
    '<!-- Generated by scripts/build.mjs. Edit data/prompts/*.json and data/site.json. -->',
    `<a href="${site.url}"><img src="assets/banner.svg" width="100%" alt="Awesome GPT Image 2.5 Prompts — curated by Image 2.5"></a>`,
    '', '# Awesome GPT Image 2.5 Prompts', '',
    `[![Validate](${site.repository}/actions/workflows/validate.yml/badge.svg)](${site.repository}/actions/workflows/validate.yml) [![Prompts](${badge('prompts', String(entries.length), '3456CE')})](#collection) [![Source checked](${badge('source checked', date, '202824')})](docs/CURATION.md) [![MIT tooling](${badge('tooling', 'MIT', '3456CE')})](LICENSE)`,
    '', '**[English](README.md) · [简体中文](README.zh-CN.md)**', '',
    t('A curated collection of **GPT Image 2.5 prompts**, source examples, and practical creative workflows. Start with the image you want to make, copy a prompt, and check exactly which references it needs.', '精选 **GPT Image 2.5 提示词**、原帖示例与实用创作工作流。从想制作的图片出发，复制提示词，并确认所需参考图。'), '',
    t(`Maintained by **[Image 2.5](${site.url})** — **[image-2-5.com](${site.url})**. Explore the collection here, then [open Image 2.5](${site.promptDestination}) to use a prompt in your image workflow.`, `由 **[Image 2.5](${site.url})** 维护 — **[image-2-5.com](${site.url})**。在这里寻找灵感，再[打开 Image 2.5](${site.promptDestination})，将提示词用于图片创作。`), '',
    t(`**${entries.length} cases · ${site.categories.length} categories · ${original} original English prompts · ${entries.length - original} labeled adaptations.** Every entry links to its creator and source. Public X metrics are dated observations, not a live ranking or an independent quality test.`, `**${entries.length} 个案例 · ${site.categories.length} 个分类 · ${original} 条原始英文提示词 · ${entries.length - original} 条明确标注的改写。** 每条均链接到创作者和来源。X 公开数据是带日期的快照，不是实时榜单，也不是独立质量测试。`), '',
    t('All launch entries are **source-checked, not independently generated or tested by this repository**. Creator result previews illustrate the source posts; they do not prove that an edited recipe reproduces those exact images.', '首批条目均为**原帖已核对，本仓库尚未独立生图测试**。创作者结果预览对应原帖，不代表改写后的配方能够复现同一张图片。'), '',
    t('[Browse the collection](#collection) · [How to use](#how-to-use) · [Data for your app](#data-for-your-app) · [Contribute](CONTRIBUTING.md) · [Support](#support)', '[浏览目录](#collection) · [使用方法](#how-to-use) · [网站数据](#data-for-your-app) · [参与贡献](CONTRIBUTING.md) · [支持项目](#support)'), '',
    `## ${t('Featured starting points', '精选起点')}`, '',
  ];
  for (const e of ordered.filter(e => e.featured)) {
    lines.push(`### [${e.title[lang]}](${link(e.id, lang)})`, '', preview(e, lang), '', e.summary[lang], '',
      `**${kind(e, lang)}** · ${mode(e, lang)} · [@${e.source.author}](${e.source.url}) · ${fmt(e.engagement.likes)} ${t('likes', '赞')} · ${fmt(e.engagement.bookmarks)} ${t('bookmarks', '收藏')} · ${fmt(e.engagement.views)} ${t('views', '浏览')}`, '',
      t(`[Copy the prompt and read the steps](${link(e.id)}) · [Open Image 2.5](${site.promptDestination})`, `[复制提示词并查看步骤](${link(e.id, 'zh')}) · [打开 Image 2.5](${site.promptDestination})`), '');
  }
  lines.push('<a id="how-to-use"></a>', `## ${t('How to use', '使用方法')}`, '',
    t('1. Choose a case and open its detail page. Copy the English prompt or the Chinese translation.', '1. 选择案例并打开详情页，复制英文提示词或中文译文。'),
    t('2. Supply the listed reference images. For multi-step workflows, follow the input/output order.', '2. 提供条目要求的参考图。多步骤工作流需按输入、输出顺序执行。'),
    t(`3. [Open Image 2.5](${site.promptDestination}) and paste the prompt into the appropriate image workflow. Links currently open the homepage; they do not automatically prefill a prompt.`, `3. [打开 Image 2.5](${site.promptDestination})，把提示词粘贴到适合的图片创作流程。当前链接进入首页，不会自动填入提示词。`),
    t('4. Inspect the result. GIF recipes also need frame splitting, alignment, and file-processing tools; these exports are not promised by the homepage link.', '4. 检查结果。GIF 配方还需要拆帧、对齐和文件处理工具；首页链接不代表已提供这些导出能力。'), '',
    t('**Prompt labels:** “Original prompt” preserves the source English wording; its Chinese block is a translation. “Editor adaptation” is our reusable rewrite of a published prompt or workflow, not the creator’s exact text. Required inputs, provenance notes, and original links live on each detail page.', '**提示词标签：**“原始英文 prompt”保留来源英文措辞，中文块为译文。“编辑改写”是我们依据公开提示词或流程整理的可复用版本，不是作者原文。每个详情页均列出输入要求、来源说明与原始链接。'), '',
    '<a id="collection"></a>', `## ${t('Collection', '完整目录')}`, '',
    t(`Snapshot: **${date} (UTC)**. Sorted by observed likes within each category for discovery, with no minimum-like admission rule. “—” means unavailable, not zero. See [curation rules](docs/CURATION.md).`, `快照日期：**${date}（UTC）**。各分类按已观察到的点赞数排列，方便发现内容；不设点赞准入门槛。“—”表示无法取得，并非零。详见[收录规则](docs/CURATION.md)。`), '');
  for (const c of site.categories) {
    lines.push(`### ${c[lang]}`, '', `| ${t('Case', '案例')} | ${t('Prompt', '提示词')} | ${t('Mode', '类型')} | ${t('Likes', '赞')} | ${t('Saves', '收藏')} | ${t('Views', '浏览')} |`, '| --- | --- | --- | ---: | ---: | ---: |');
    for (const e of ordered.filter(e => e.category === c.id)) lines.push(`| [${table(e.title[lang])}](${link(e.id, lang)}) | ${kind(e, lang)} | ${mode(e, lang)} | ${fmt(e.engagement.likes)} | ${fmt(e.engagement.bookmarks)} | ${fmt(e.engagement.views)} |`);
    lines.push('');
  }
  lines.push('<a id="data-for-your-app"></a>', `## ${t('Data for your app', '网站可复用数据')}`, '',
    t('The human-readable collection and machine-readable catalog share one source of truth:', '阅读目录与机器可读目录使用同一份源数据：'), '',
    t('- [`data/prompts/`](data/prompts/): one JSON file per stable prompt ID, with bilingual text, inputs, source links, tags, model evidence, and metric timestamps.', '- [`data/prompts/`](data/prompts/)：每个稳定 ID 对应一份 JSON，包含双语文本、输入要求、原帖、标签、模型依据与指标时间。'),
    t('- [`data/catalog.json`](data/catalog.json): generated catalog for search, category filters, prompt copying, and future website integration.', '- [`data/catalog.json`](data/catalog.json)：生成的统一目录，可用于搜索、分类筛选、复制提示词与后续网站集成。'),
    t('- [`data/site.json`](data/site.json): shared branding and website destination. Updating `promptDestination` changes every generated “Open Image 2.5” link.', '- [`data/site.json`](data/site.json)：共用品牌和网站入口。修改 `promptDestination` 会更新所有生成的“打开 Image 2.5”链接。'), '',
    '```bash', 'node --version # Node.js 22+', 'npm run build', 'npm run check', '```', '',
    t('No package installation, database, API key, or paid service is needed to contribute. Read the [data contract](docs/DATA_FORMAT.md) and [roadmap](docs/ROADMAP.md).', '参与贡献无需安装依赖、数据库、API Key 或付费服务。可阅读[数据格式](docs/DATA_FORMAT.md)与[路线图](docs/ROADMAP.md)。'), '',
    `## ${t('Contribute a prompt', '贡献提示词')}`, '',
    t(`Found something useful? [Submit the original post](${site.repository}/issues/new?template=prompt.yml) or open a focused PR. Include the prompt, creator, result, references needed, and any dated metrics you can verify. Low-engagement discoveries are welcome.`, `发现好案例后，可以[提交原帖](${site.repository}/issues/new?template=prompt.yml)或发起范围清晰的 PR。请提供提示词、创作者、结果、所需参考图，以及能够核对的带日期指标。也欢迎低热度但实用的发现。`), '',
    t('See [CONTRIBUTING.md](CONTRIBUTING.md), [Code of Conduct](CODE_OF_CONDUCT.md), and [content corrections and removal](CONTENT_POLICY.md). English Conventional Commits and automated data checks keep contributions reviewable.', '请参阅[贡献指南](CONTRIBUTING.md)、[行为准则](CODE_OF_CONDUCT.md)与[内容纠错和移除规则](CONTENT_POLICY.md)。使用英文 Conventional Commits 与自动数据检查，便于审核贡献。'), '',
    '<a id="support"></a>', `## ${t('Maintained and supported by Image 2.5', '由 Image 2.5 维护与支持')}`, '',
    `<a href="${site.url}"><img src="assets/brand/image25-logo.svg" width="180" alt="Image 2.5"></a>`, '',
    t(`**[Image 2.5 — image-2-5.com](${site.url})** maintains this open-source collection. If it helps your creative work, visit the website, star the repository, or contribute a useful prompt. The GitHub Sponsor button also links to Image 2.5.`, `**[Image 2.5 — image-2-5.com](${site.url})** 维护这个开源合集。如果它对创作有帮助，可以访问网站、为仓库点 Star，或贡献实用提示词。GitHub Sponsor 按钮也指向 Image 2.5。`), '',
    t(`Project: **[image-2-5.com](${site.url})** · Contact: **[${site.contact}](mailto:${site.contact})**`, `项目网站：**[image-2-5.com](${site.url})** · 联系方式：**[${site.contact}](mailto:${site.contact})**`), '',
    `## ${t('Credits and licenses', '致谢与许可')}`, '',
    t('Inspired by the visual, source-linked format of [Awesome GPT-4o Images](https://github.com/jamez-bondos/awesome-gpt4o-images), [Awesome Nano Banana Images](https://github.com/PicoTrex/Awesome-Nano-Banana-images), [YouMind](https://youmind.com/nano-banana-pro-prompts), and the browsing experience of [Meigen](https://www.meigen.ai/). Discovery references are listed in [ACKNOWLEDGEMENTS.md](ACKNOWLEDGEMENTS.md). Each case credits its own primary creator.', '参考了 [Awesome GPT-4o Images](https://github.com/jamez-bondos/awesome-gpt4o-images)、[Awesome Nano Banana Images](https://github.com/PicoTrex/Awesome-Nano-Banana-images)、[YouMind](https://youmind.com/nano-banana-pro-prompts) 的图文与来源呈现方式，以及 [Meigen](https://www.meigen.ai/) 的浏览体验。发现渠道见[致谢文件](ACKNOWLEDGEMENTS.md)，每个案例单独署名原始创作者。'), '',
    t('Repository tooling and original documentation use [MIT](LICENSE). Third-party prompts, example images, and trademarks retain their own rights; the repository license does not relicense them. Source images are externally linked, not bundled as an image dataset. See [CONTENT_POLICY.md](CONTENT_POLICY.md).', '仓库工具代码和原创文档采用 [MIT](LICENSE)。第三方提示词、示例图片与商标保留各自权利，仓库许可证不会重新授予它们的许可。来源图片通过外部链接展示，不打包为图片数据集。详见[内容规则](CONTENT_POLICY.md)。'), '',
    t('Image 2.5 is an independent project. GPT Image 2.5 is an OpenAI model family; this repository is not affiliated with or endorsed by OpenAI. [Official model announcement](https://openai.com/index/introducing-chatgpt-images-2-5/).', 'Image 2.5 是独立项目。GPT Image 2.5 是 OpenAI 的模型系列；本仓库与 OpenAI 无隶属关系，也未获其背书。[官方模型公告](https://openai.com/index/introducing-chatgpt-images-2-5/)。'), '');
  return lines.join('\n');
}

function detail(e) {
  const lines = ['<!-- Generated by scripts/build.mjs. Edit the corresponding data/prompts JSON. -->', `# ${e.title.en}`, '', `[All prompts](../README.md#collection) · [中文](#中文) · [Open Image 2.5](${site.promptDestination})`, '', e.summary.en, '',
    `**${kind(e, 'en')} · ${mode(e, 'en')} · Source-checked ${e.source.checked_at.slice(0, 10)} · Not independently tested**`, '', preview(e, 'en', 560), '',
    `Source example by [@${e.source.author}](${e.source.url}). ${e.prompt.kind === 'original' ? 'The example belongs to the original post; results can vary.' : 'This is the creator’s source result, not a verified output of the adapted prompt below.'}`, '',
    '## Prompt', ''];
  for (const [i, s] of e.prompt.steps.entries()) lines.push(e.prompt.steps.length > 1 ? `### Step ${i + 1}` : '', '', '```text', s.en, '```', '');
  lines.push('## Required inputs', '', ...(e.inputs.length ? e.inputs.map(v => `- ${v.en}`) : ['No reference image is specified by the source.']), '', '## Notes', '', ...e.notes.map(v => `- ${v.en}`), '',
    `[Open Image 2.5](${site.promptDestination}) and paste the prompt into the appropriate image workflow. This link currently opens the homepage and does not prefill the prompt. GIF and file-export recipes need additional processing tools.`, '',
    '## Source and evidence', '', `- Creator: [@${e.source.author}](https://x.com/${e.source.author})`, `- [Showcase post](${e.source.url})`, `- [Prompt or workflow source](${e.source.prompt_url})`,
    `- Model: ${e.model.family}; variant ${e.model.variant ?? 'not specified in the verified source'}.`, `- Model evidence: [creator’s statement](${e.model.evidence_url}); output model not independently verified.`,
    `- Checked at: ${e.source.checked_at}`, `- Independent generation test: ${e.verification.independently_tested ? e.verification.test_url : 'none'}`, ...(e.source.disclosure ? [`- Disclosure: ${e.source.disclosure}`] : []), '',
    '### Public engagement snapshot', '', '| Likes | Reposts | Replies | Bookmarks | Views |', '| ---: | ---: | ---: | ---: | ---: |', `| ${['likes', 'reposts', 'replies', 'bookmarks', 'views'].map(k => fmt(e.engagement[k])).join(' | ')} |`, '',
    `Observed on the showcase post at **${e.engagement.observed_at}**, through ${e.engagement.method}. “—” means unavailable. These counts can change.`, '',
    '## 中文', '', `### ${e.title.zh}`, '', e.summary.zh, '', `**${kind(e, 'zh')} · ${mode(e, 'zh')} · 已核对原帖 · 尚未独立生图测试**`, '',
    '预览是原作者帖中的示例，并非本仓库使用下方提示词重新生成的结果。', '', '### 提示词', '');
  for (const [i, s] of e.prompt.steps.entries()) lines.push(e.prompt.steps.length > 1 ? `步骤 ${i + 1}：` : '', '', '```text', s.zh, '```', '');
  lines.push('### 输入要求', '', ...(e.inputs.length ? e.inputs.map(v => `- ${v.zh}`) : ['原帖未指定参考图。']), '', '### 使用说明', '', ...e.notes.map(v => `- ${v.zh}`), '',
    `[打开 Image 2.5](${site.promptDestination})，将提示词粘贴到适合的图片创作流程。链接当前进入首页，不会自动填入提示词。GIF 与文件导出配方还需要额外处理工具。`, '',
    `来源：[@${e.source.author}](${e.source.url}) · [提示词或工作流原文](${e.source.prompt_url})。模型由作者声明，仓库未独立核实生成模型${e.model.variant ? `，版本为 ${e.model.variant}` : '，具体版本未说明'}。`, '',
    `公开数据快照（${e.engagement.observed_at}）：${fmt(e.engagement.likes)} 赞、${fmt(e.engagement.reposts)} 转帖、${fmt(e.engagement.replies)} 回复、${fmt(e.engagement.bookmarks)} 收藏、${fmt(e.engagement.views)} 浏览。“—”为未知，数据会变化。`, '',
    '---', '', `Maintained by **[Image 2.5 — image-2-5.com](${site.url})**. Third-party prompts and source media retain their creators’ rights. [Content policy](../CONTENT_POLICY.md) · [Suggest a correction](${site.repository}/issues/new?template=content.yml)`, '',
    `由 **[Image 2.5 — image-2-5.com](${site.url})** 维护。第三方提示词与示例媒体保留创作者权利。`, '');
  return lines.join('\n');
}

outputs.set('README.md', readme('en'));
outputs.set('README.zh-CN.md', readme('zh'));
for (const e of entries) outputs.set(`prompts/${e.id}.md`, detail(e));
outputs.set('data/catalog.json', JSON.stringify({ schema_version: 1, source_checked_through: date, website: site.url, prompt_destination: site.promptDestination, repository: site.repository, categories: site.categories, entries: ordered }, null, 2) + '\n');
const stale = [];
const check = process.argv.includes('--check');
for (const [file, content] of outputs) {
  const full = path.join(root, file);
  if (check) {
    if (!fs.existsSync(full) || fs.readFileSync(full, 'utf8') !== content) stale.push(file);
  } else {
    fs.mkdirSync(path.dirname(full), { recursive: true });
    fs.writeFileSync(full, content);
  }
}
const promptDir = path.join(root, 'prompts');
if (fs.existsSync(promptDir)) for (const file of fs.readdirSync(promptDir).filter(f => f.endsWith('.md'))) {
  if (!outputs.has(`prompts/${file}`)) {
    if (check) stale.push(`prompts/${file} (orphan)`);
    else fs.unlinkSync(path.join(promptDir, file));
  }
}
if (stale.length) { console.error(`Generated files are stale. Run npm run build:\n${stale.join('\n')}`); process.exitCode = 1; }
else console.log(`${check ? 'Checked' : 'Generated'} ${outputs.size} catalog and documentation files.`);
